### ISSUE TITLE
Magic-Folder depends on deprecated `appdirs` package

### ISSUE THREAD

**Issue by crwood** [tahoe-lafs/magic-folder#760]
As per https://github.com/ActiveState/appdirs, the `appdirs` package (which is currently used by magic-folder but has not seen a release since 2020) is officially deprecated:

>Note: This project has been officially deprecated. You may want to check out https://pypi.org/project/platformdirs/ which is a more active fork of appdirs.

**Comment by meejah** [comment]
`platformdirs` should be a drop-in replacement, we only use `user_config_dir`.
